#!/bin/sh
#
#  boostit: Boosts the package for the first time
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License along
#  with this program; if not, write to the Free Software Foundation, Inc.,
#  51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
#  (C) Copyright 2010 Sercan Arslan
#

. /etc/init.d/tc-functions

TCEXTTOOLS_ROOT=$(dirname $0)/..

if [ -f "$TCEXTTOOLS_ROOT"/etc/tc-ext-tools/functions ]; then
     . "$TCEXTTOOLS_ROOT"/etc/tc-ext-tools/functions
else
     echo "${RED}$(basename $0):${BLUE} tc-ext-tools functions file not found!${NORMAL}"
     exit 1
fi

PACKAGE="$1"
VERSION="$2"
EXTENSIONS="$3"

print_usage(){
  echo -e "${TCEXTTOOLS_ERROR_COLOR}Usage:${TCEXTTOOLS_MESSAGE_COLOR}\n$(basename $0) package version \"extension1 extension2 ...\"${NORMAL}"
}

if [ -z "$PACKAGE" ] || [ -z "$VERSION" ] || [ -z "$EXTENSIONS" ]; then
     print_usage
     exit 1
fi

print_it "You entered:\n\n\tPACKAGE=$PACKAGE\n\tVERSION=$VERSION\n\tEXTENSIONS=$EXTENSIONS\n"

if [ -e "$PACKAGE_COMMON" ]; then
     print_it warning "Warning! This package looks to be boosted before.\nIf you continue existing files will be overwritten.\nWould you like you continue ? [y or n]"
     read ans
     case "$ans" in
          y)
            print_it "You agreed to continue. The files will be overwritten."
            ;;
          n)
            print_it "You don't want to continue ? Farewell then!"
            exit 0
            ;;
          *) 
            print_it error "I don't understand what you are saying!"
            exit 1
            ;;
     esac
fi

this_main() {

  if [ ! -d "$PACKAGE_EXTENSIONS" ]; then
       install -m 755 -d $PACKAGE_EXTENSIONS || return 1
  fi

  if [ "$VERSION" = "svn" ]; then

       cat > $PACKAGE_COMMON << _EOF
PACKAGE="$PACKAGE"
VERSION="svn\${YEAR}\${MONTH}\${DAY}"
TOP_SRC="\${PACKAGE}-\${VERSION}"
SOURCE="\${TOP_SRC}.tar.xz"
SOURCE_URL=""
SOURCE_SVN="true"
ICON=""
DESKTOP_ENTRY=""
BUILD_DEPENDS=""

EXTENSIONS="$EXTENSIONS"
DESCRIPTION="A brief description of package."
AUTHOR="authors of package"
SITE="http://www.package.com"
COPYING="GPL-2"
MAINTAINERS="$PACKAGE_MAINTAINER"
COMMENTS="This extension is PPI compatible."
CHANGELOG="---"
CURRENT="First Version"
_EOF

       [ "$?" -gt 0 ] && return 1

  elif [ "$VERSION" = "git" ]; then

       cat > $PACKAGE_COMMON << _EOF
PACKAGE="${PACKAGE}"
VERSION="git\${YEAR}\${MONTH}\${DAY}"
TOP_SRC="\${PACKAGE}-\${VERSION}"
SOURCE="\${TOP_SRC}.tar.xz"
SOURCE_URL=""
SOURCE_GIT="true"
ICON=""
DESKTOP_ENTRY=""
BUILD_DEPENDS=""

EXTENSIONS="$EXTENSIONS"
DESCRIPTION="A brief description of package."
AUTHOR="authors of package"
SITE="http://www.package.com"
COPYING="GPL-2"
MAINTAINERS="$PACKAGE_MAINTAINER"
COMMENTS="This extension is PPI compatible."
CHANGELOG="---"
CURRENT="First Version"
_EOF

       [ "$?" -gt 0 ] && return 1

  else

       cat > $PACKAGE_COMMON << _EOF
PACKAGE="$PACKAGE"
VERSION="$VERSION"
SOURCE="\${PACKAGE}-\${VERSION}.tar.bz2"
TOP_SRC="\${PACKAGE}-\${VERSION}"
SOURCE_URL=""
ICON=""
DESKTOP_ENTRY=""
BUILD_DEPENDS=""

EXTENSIONS="$EXTENSIONS"
DESCRIPTION="A brief description of package."
AUTHOR="authors of package"
SITE="http://www.package.com"
COPYING="GPL-2"
MAINTAINERS="$PACKAGE_MAINTAINER"
COMMENTS="This extension is PPI compatible."
CHANGELOG="---"
CURRENT="First Version"
_EOF

       [ "$?" -gt 0 ] && return 1

  fi

  install -m 644 "$TCEXTTOOLS_ROOT"/share/tc-ext-tools/build $PACKAGE_BUILD || return 1

  for EXTENSION in $EXTENSIONS
  do
      mkdir -p "$PACKAGE_EXTENSIONS"/"$EXTENSION" || return 1
      touch "$PACKAGE_EXTENSIONS"/"$EXTENSION"/install || return 1
      if [ "${EXTENSION%-doc}" = "$EXTENSION" ]; then
           touch "$PACKAGE_EXTENSIONS"/"$EXTENSION"/dep || return 1
      fi
      if [ ! "${EXTENSION%-locale}" = "$EXTENSION" ]; then
           echo "${EXTENSION%-locale}.tcz" > "$PACKAGE_EXTENSIONS"/"$EXTENSION"/dep || return 1
      elif [ ! "${EXTENSION%-dev}" = "$EXTENSION" ]; then
           echo "${EXTENSION%-dev}.tcz" > "$PACKAGE_EXTENSIONS"/"$EXTENSION"/dep || return 1
      fi

  done

  return 0
}

print_it "Boosting the package $PACKAGE ... \c"
this_main > /dev/null 2>&1
if [ "$?" -gt 0 ]; then
     print_it error "failed!"
     exit 1
fi
print_it hilight "successful!"

exit 0
