#!/bin/sh

############################################################################
#                                                                          #
#  compressit: Compresses the directory or file with a compression format  #
#                                                                          #
############################################################################

#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License along
#  with this program; if not, write to the Free Software Foundation, Inc.,
#  51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
#  (C) Copyright 2011 Sercan Arslan
#

. /etc/init.d/tc-functions

TCEXTTOOLS_ROOT="$(dirname $0)/.."

if [ -f "$TCEXTTOOLS_ROOT/etc/init.d/tc-ext-tools.sh" ]; then
     . "$TCEXTTOOLS_ROOT/etc/init.d/tc-ext-tools.sh"
else
     echo "${RED}$(basename $0):${BLUE} tc-ext-tools functions file not found!${NORMAL}"
     exit 1
fi

FORMAT="$1"
TARGET="$2"
OPTIONS="$3"

print_usage(){

   echo -e "${TCEXTTOOLS_ERROR_COLOR}${THIS} usage:\n\t${TCEXTTOOLS_MESSAGE_COLOR}${THIS} gz|bz2|xz /path/to/target options${NORMAL}"

}

if [ -z "$TARGET" ] || [ -z "$FORMAT" ]; then
     print_usage
     exit 1
fi

############################################################################ 
#            compresses the target with a compression format               #
############################################################################

this_compress() {

   if [ -d "$TARGET" ]; then
        TOP_DIR="$(basename $TARGET)"
        OUTPUT="${TOP_DIR}.tar.${FORMAT}"
        [ -e "$OUTPUT" ] && sudo rm -f "$OUTPUT"
        tar "$OPTIONS" -C "$(dirname $TARGET)" -cv${XYZ}f "$OUTPUT" "$TOP_DIR" || return 1
   elif [ -f "$TARGET" ]; then
        OUTPUT="$(basename $TARGET).${FORMAT}"
        [ -e "$OUTPUT" ] && sudo rm -f "$OUTPUT"
        "$COMPRESSOR" -c "$TARGET" > "$OUTPUT" || return 1
   fi

   return 0

}

############################################################################ 
#                                this main                                 #
############################################################################

this_main() {

   case "$FORMAT" in
        bz2)
            COMPRESSOR="bzip2"
            XYZ=j
            this_compress || return 1
            ;;
        gz)
            COMPRESSOR="gzip"
            XYZ="z"
            this_compress || return 1
            ;;
        xz)
            COMPRESSOR="xz"
            XYZ="J"
            this_compress || return 1
            ;;
        *)
            return 1
            ;;
   esac

   return 0

}

print_it "Compressing the target $TARGET with the compression format $FORMAT ... \c"
this_main > "$TCEXTTOOLS_MESSAGE_LOG_2" 2>&1
if [ "$?" -gt 0 ]; then
     print_it error "failed!"
     exit 1
fi
print_it hilight "successful!"

exit 0

