#!/bin/sh

############################################################################
#                                                                          #
#                       compileit: compiles the package                    #
#                                                                          #
############################################################################

#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#  Copyright (c) 2011 Sercan Arslan <arslanserc@gmail.com>
#

. /etc/init.d/tc-functions

TCEXTTOOLS_ROOT="$(dirname $0)/.."

if [ -f "$TCEXTTOOLS_ROOT/etc/tc-ext-tools/functions" ]; then
     . "$TCEXTTOOLS_ROOT/etc/tc-ext-tools/functions"
else
     echo "${RED}$(basename $0):${BLUE} tc-ext-tools functions file not found!${NORMAL}"
     exit 1
fi

if [ ! -d "$PACKAGE_SOURCE_TOPDIR" ]; then
       print_it --error "You must configure it first!"
       exit 1
fi

this_main() {

   echo "---------------------------------------------------------------"
   echo ""
   echo "Compiling the package $PACKAGE ..."
   echo ""
   echo "---------------------------------------------------------------"

   echo "---------------------------------------------------------------"
   echo "Executing the package build compile function."
   echo "---------------------------------------------------------------"
   cd "$PACKAGE_SOURCE_TOPDIR"
   build_compile > "$PACKAGE_COMPILE_LOG" 2>&1 || return 1

   echo "---------------------------------------------------------------"
   echo ""
   echo "Compiled the package $PACKAGE successfully."
   echo "For details: buildit print compile"
   echo ""
   echo "---------------------------------------------------------------"

   return 0

}

print_it "Compiling the package $PACKAGE ... \c"
this_main > "$PACKAGE_MESSAGE_LOG" 2>&1
if [ "$?" -gt 0 ]; then
     print_it --error "failed!"
     exit 1
fi
print_it --hilight "successful!"

exit 0

