#!/bin/sh

############################################################################
#                                                                          #
#               createit: Creates the package extensions                   #
#                                                                          #
############################################################################

#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License along
#  with this program; if not, write to the Free Software Foundation, Inc.,
#  51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
#  (C) Copyright 2011 Sercan Arslan
#

. /etc/init.d/tc-functions

TCEXTTOOLS_ROOT="$(dirname $0)/.."

if [ -f "$TCEXTTOOLS_ROOT/etc/init.d/tc-ext-tools.sh" ]; then
     . "$TCEXTTOOLS_ROOT/etc/init.d/tc-ext-tools.sh"
else
     echo "${RED}$(basename $0):${BLUE} tc-ext-tools functions file not found!${NORMAL}"
     exit 1
fi

this_create() {

   if [ -f "$TCEXTTOOLS_EXTENSION_TCEINSTALLED" ]; then
        sudo install -D -m 775 "$TCEXTTOOLS_EXTENSION_TCEINSTALLED" "$TCEXTTOOLS_EXTENSION_BINDIR/usr/local/tce.installed/$EXTENSION_NAME" || return 1
        sudo chown -R root:staff "$TCEXTTOOLS_EXTENSION_BINDIR/usr/local/tce.installed" || return 1
        sudo chmod -R 775 "$TCEXTTOOLS_EXTENSION_BINDIR/usr/local/tce.installed" || return 1
   fi

   if [ -n "$ICON" ]; then
        if [ -z "$DESKTOP" ]; then
             if [ -d "$TCEXTTOOLS_EXTENSION_BINDIR/usr/share/applications" ]; then
                  DESKTOP="/usr/share/applications/${EXTENSION_NAME}.desktop"
             else
                  DESKTOP="/usr/local/share/applications/${EXTENSION_NAME}.desktop"
             fi
        fi

        if [ ! -f "$TCEXTTOOLS_EXTENSION_BINDIR/$DESKTOP" ]; then
               print_it error "The desktop file for the package $PACKAGE extension $EXTENSION_NAME not found!"
               return 1
        else
             if [ ! $(grep "X-FullPathIcon=" "$TCEXTTOOLS_EXTENSION_BINDIR/$DESKTOP") ]; then
                    sudo sh -c "echo \"X-FullPathIcon=$ICON\" >> $TCEXTTOOLS_EXTENSION_BINDIR/$DESKTOP" || return 1
             fi
        fi
   fi

   cd "$TCEXTTOOLS_BIN"

   sudo rm -f *.tcz*

   sudo mksquashfs "$EXTENSION_NAME" "${EXTENSION_NAME}.tcz" || return 1

   md5sum "${EXTENSION_NAME}.tcz" > "${EXTENSION_NAME}.tcz.md5.txt" || return 1

   cd "$TCEXTTOOLS_EXTENSION_BINDIR"
   for i in $(ls)
   do
       sudo find "$i" -not -type d >> "$TCEXTTOOLS_BIN/${EXTENSION_NAME}.tcz.list"
   done

   [ -d "$TCEXTTOOLS_EXTENSION_PKGDIR" ] || mkdir -p "$TCEXTTOOLS_EXTENSION_PKGDIR"

   busybox cp -f "$TCEXTTOOLS_BIN/${EXTENSION_NAME}".tcz* "$TCEXTTOOLS_EXTENSION_PKGDIR" || return 1

   if [ -e "$PACKAGE_EXTENSION_DEP" ]; then
        install -m 644 "$PACKAGE_EXTENSION_DEP" "$TCEXTTOOLS_EXTENSION_DEP" || return 1
   fi

   sudo rm -f "$TCEXTTOOLS_BIN"/*.tcz*

   return 0

}

this_main() {

   [ -d "$TCEXTTOOLS_PKG" ] && sudo rm -rf "$TCEXTTOOLS_PKG"
   mkdir -p "$TCEXTTOOLS_PKG"

   for EXTENSION in $EXTENSIONS
   do
       set_extension || return 1

       if [ ! -d "$TCEXTTOOLS_EXTENSION_BINDIR" ]; then
              print_it error "You must split it first!"
              exit 1
       fi

       this_create
       if [ "$?" -gt 0 ]; then
            print_it error "Creating the package $PACKAGE extension $EXTENSION_NAME failed!"
            return 1
       else
            print_it "Creating the package $PACKAGE extension $EXTENSION_NAME successful!"
       fi
   done

   return 0

}

print_it "Creating the package $PACKAGE extensions ... \c"
this_main > "$TCEXTTOOLS_MESSAGE_LOG_2" 2>&1
if [ "$?" -gt 0 ]; then
     print_it error "failed!"
     exit 1
fi
print_it hilight "successful!"

exit 0

