#!/bin/sh

############################################################################
#                                                                          #
#       encryptit: Encrypts the file with the default encryption key       #
#                                                                          #
############################################################################

#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#  Copyright (c) 2011 Sercan Arslan <arslanserc@gmail.com>
#

. /etc/init.d/tc-functions

TCEXTTOOLS_ROOT="$(dirname $0)/.."

if [ -f "$TCEXTTOOLS_ROOT/etc/init.d/tc-ext-tools.sh" ]; then
     . "$TCEXTTOOLS_ROOT/etc/init.d/tc-ext-tools.sh"
else
     echo "${RED}$(basename $0):${BLUE} tc-ext-tools functions file not found!${NORMAL}"
     exit 1
fi

if [ ! -f "$PACKAGE_PACKAGE" ]; then
       print_it error "You must package it first!"
       exit 1
fi

this_main() {

   echo "---------------------------------------------------------------" > "$PACKAGE_MESSAGE_LOG_2"
   echo "" >> "$PACKAGE_MESSAGE_LOG_2"
   echo "Encrypting the package $PACKAGE ..." >> "$PACKAGE_MESSAGE_LOG_2"
   echo "" >> "$PACKAGE_MESSAGE_LOG_2"
   echo "---------------------------------------------------------------" >> "$PACKAGE_MESSAGE_LOG_2"

   echo -e "Checking if the package $PACKAGE tarball encrypted exists ... \c" >> "$PACKAGE_MESSAGE_LOG_2"
   if [ -f "$PACKAGE_PACKAGE_ENCRYPTED" ]; then
        echo "yes" >> "$PACKAGE_MESSAGE_LOG_2"
        echo "Removing the package $PACKAGE tarball encrypted." >> "$PACKAGE_MESSAGE_LOG_2"
        sudo rm -f "$PACKAGE_PACKAGE_ENCRYPTED"
   else
        echo "no" >> "$PACKAGE_MESSAGE_LOG_2"
   fi

   echo "---------------------------------------------------------------" >> "$PACKAGE_MESSAGE_LOG_2"
   echo "Running bcrypt to encrypt the package $PACKAGE tarball."  >> "$PACKAGE_MESSAGE_LOG_2"
   echo "---------------------------------------------------------------" >> "$PACKAGE_MESSAGE_LOG_2"
   print_it "Please enter the encryption key: \c"
   print_it hilight "$PACKAGE_ENCRYPTION_KEY"
   bcrypt "$PACKAGE_PACKAGE"

   if [ "$?" -gt 0 ]; then
        echo "---------------------------------------------------------------" >> "$PACKAGE_MESSAGE_LOG_2"
        echo "" >> "$PACKAGE_MESSAGE_LOG_2"
        echo "Encrypting the package $PACKAGE failed." >> "$PACKAGE_MESSAGE_LOG_2"
        echo "" >> "$PACKAGE_MESSAGE_LOG_2"
        echo "---------------------------------------------------------------" >> "$PACKAGE_MESSAGE_LOG_2"
        return 1
   else
        echo "---------------------------------------------------------------" >> "$PACKAGE_MESSAGE_LOG_2"
        echo "" >> "$PACKAGE_MESSAGE_LOG_2"
        echo "Encrypted the package $PACKAGE successfully." >> "$PACKAGE_MESSAGE_LOG_2"
        echo "" >> "$PACKAGE_MESSAGE_LOG_2"
        echo "---------------------------------------------------------------" >> "$PACKAGE_MESSAGE_LOG_2"
   fi

   return 0

}

print_it "Encrypting the package $PACKAGE ..."
this_main
if [ "$?" -gt 0 ]; then
     print_it error "Encrypting the package $PACKAGE failed!"
     exit 1
fi

exit 0

