#!/bin/sh

############################################################################
#                                                                          #
#       loadit: Loads the extensions required to build the package         #
#                                                                          #
############################################################################

#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License along
#  with this program; if not, write to the Free Software Foundation, Inc.,
#  51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
#  (C) Copyright 2011 Sercan Arslan
#

. /etc/init.d/tc-functions

TCEXTTOOLS_ROOT="$(dirname $0)/.."

if [ -f "$TCEXTTOOLS_ROOT/etc/init.d/tc-ext-tools.sh" ]; then
        . "$TCEXTTOOLS_ROOT/etc/init.d/tc-ext-tools.sh"
else
        echo "${RED}$(basename $0):${BLUE} tc-ext-tools functions file not found!${NORMAL}"
        exit 1
fi

############################################################################ 
#                              load extension                              #
############################################################################

tcz_load() {

   if [ -n "$EXTENSION" ]; then
        if [ "${EXTENSION#\#}" = "$EXTENSION" ]; then
             if [ ! -e "$TCE_DIR/optional/${EXTENSION%.tcz}.tcz" ]; then
                    tce-load -w "${EXTENSION%.tcz}.tcz" || return 1
             fi
             if [ ! -e "/usr/local/tce.installed/${EXTENSION%.tcz}" ]; then
                    tce-load -i "${EXTENSION%.tcz}.tcz" || return 1
             fi
        fi
   fi

   return 0

}

############################################################################ 
#                                this main                                 #
############################################################################

this_main() {

   if [ -n "$BUILD_DEPENDS" ]; then
        BUILD_DEPENDS="$TCEXTTOOLS_DEPENDS $BUILD_DEPENDS"
   else
        BUILD_DEPENDS="$TCEXTTOOLS_DEPENDS"
   fi

   for EXTENSION in $BUILD_DEPENDS
   do
       tcz_load || return 1
   done

   return 0

}

print_it "Loading the extensions ... \c"
this_main > "$TCEXTTOOLS_MESSAGE_LOG_2" 2>&1
if [ "$?" -gt 0 ]; then
     print_it error "failed!"
     exit 1
fi
print_it hilight "successful!"

exit 0

