#!/bin/sh
#
#  modifyit: Modifies the package
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License along
#  with this program; if not, write to the Free Software Foundation, Inc.,
#  51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
#  (C) Copyright 2010 Sercan Arslan
#

. /etc/init.d/tc-functions

TCEXTTOOLS_ROOT=$(dirname $0)/..

if [ -f "$TCEXTTOOLS_ROOT"/etc/tc-ext-tools/functions ]; then
     . "$TCEXTTOOLS_ROOT"/etc/tc-ext-tools/functions
else
     echo "${RED}$(basename $0):${BLUE} tc-ext-tools functions file not found!${NORMAL}"
     exit 1
fi

if [ ! -d "$TCEXTTOOLS_INSTALL_ROOT" ]; then
     print_it error "You must install it first!"
     exit 1
fi

this_main() {

  # We need to convert symlinks to full path for gnome help browser files
  if [ -d "$TCEXTTOOLS_INSTALL_ROOT"/usr/local/share/gnome/help ]; then
       for l in $(sudo find "$TCEXTTOOLS_INSTALL_ROOT"/usr/local/share/gnome/help -type l)
       do
           FILE=$(sudo busybox readlink -f "$l")
           LINK="${FILE#${TCEXTTOOLS_INSTALL_ROOT}}"
           sudo busybox ln -sf "$LINK" "$l" || return 1
       done
  fi
  #

  # Add wbar icon if ICON variable is set
  if [ -n "$ICON" ]; then
       if [ ! -e "$TCEXTTOOLS_INSTALL_ROOT"/"$ICON" ]; then
            print_it error "The icon: $TCEXTTOOLS_INSTALL_ROOT/$ICON does not exist!"
            return 1
       elif [ ! -e "$TCEXTTOOLS_INSTALL_ROOT"/"$DESKTOP_ENTRY" ]; then
            print_it error "The desktop entry: $TCEXTTOOLS_INSTALL_ROOT/$DESKTOP_ENTRY does not exist!"
            return 1
       else
            sudo sh -c "echo 'X-FullPathIcon=${ICON}' >> $TCEXTTOOLS_INSTALL_ROOT/$DESKTOP_ENTRY" || return 1
       fi
  fi
  #

  # Create a list of package contents so that user can choose where to put files
  [ -e "$PACKAGE_EXTENSIONS"/"${PACKAGE}.list" ] && sudo rm -f "$PACKAGE_EXTENSIONS"/"${PACKAGE}.list"

  cd $TCEXTTOOLS_INSTALL_ROOT
  for i in $(ls)
  do
      sudo find "$i" -not -type d >> "$PACKAGE_EXTENSIONS"/"${PACKAGE}.list" || return 1
  done

  return 0
}

print_it "Modifying the package $PACKAGE ... \c"
this_main > $TCEXTTOOLS_ERROR_LOG_2 2>&1
if [ "$?" -gt 0 ]; then
     print_it error "failed!"
     exit 1
fi
print_it hilight "successful!"

exit 0
