#!/bin/sh

############################################################################
#                                                                          #
#                     packageit: Packages the package                      #
#                                                                          #
############################################################################

#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License along
#  with this program; if not, write to the Free Software Foundation, Inc.,
#  51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
#  (C) Copyright 2011 Sercan Arslan
#

. /etc/init.d/tc-functions

TCEXTTOOLS_ROOT="$(dirname $0)/.."

if [ -f "$TCEXTTOOLS_ROOT/etc/init.d/tc-ext-tools.sh" ]; then
     . "$TCEXTTOOLS_ROOT/etc/init.d/tc-ext-tools.sh"
else
     echo "${RED}$(basename $0):${BLUE} tc-ext-tools functions file not found!${NORMAL}"
     exit 1
fi

this_main() {

   echo ""
   echo "Starting the packaging process of the package $PACKAGE ..."

   echo ""
   echo "Cleaning the package temporary directory."
   [ -d "$TCEXTTOOLS_PKG_TEMP" ] && sudo rm -rf "$TCEXTTOOLS_PKG_TEMP"
   mkdir -p "$TCEXTTOOLS_PKG_TEMP"

   for EXTENSION in $EXTENSIONS
   do
       echo ""
       echo "Setting the extension $EXTENSION parameters."
       set_extension || return 1

       echo ""
       echo "Processing the extension $EXTENSION_NAME ..."
       if [ ! -d "$TCEXTTOOLS_EXTENSION_PKGDIR" ]; then
              echo "You must create the package extensions first!"
              exit 1
       fi
       echo "Copying the extension $EXTENSION_NAME files to the package temporary directory."
       [ -d "$TCEXTTOOLS_PKG_TEMP/$PACKAGE/$EXTENSION_NAME" ] || mkdir -p "$TCEXTTOOLS_PKG_TEMP/$PACKAGE/$EXTENSION_NAME"
       cp -f "$TCEXTTOOLS_EXTENSION_PKGDIR"/*.tcz* "$TCEXTTOOLS_PKG_TEMP/$PACKAGE/$EXTENSION_NAME" || return 1
   done

   echo ""
   echo "Copying the package source to the package temporary directory ..."
   if [ -f "$TCEXTTOOLS_SOURCE_CONVERTED" ]; then
        echo "Converted package source detected. Using it instead of the original source."
        cp -f "$TCEXTTOOLS_SOURCE_CONVERTED" "$TCEXTTOOLS_PKG_TEMP/$PACKAGE" || return 1
   elif [ -f "$TCEXTTOOLS_SOURCE" ]; then
        cp -f "$TCEXTTOOLS_SOURCE" "$TCEXTTOOLS_PKG_TEMP/$PACKAGE" || return 1
   fi

   if [ -f "$TCEXTTOOLS_PACKAGE" ]; then
        echo ""
        echo "The package tarball detected. Deleting it."
        sudo rm -f "$TCEXTTOOLS_PACKAGE"
   fi

   echo ""
   echo "Creating the package tarball from the package temporary directory."
   echo ""
   tar -C "$TCEXTTOOLS_PKG_TEMP" -cvjf "$TCEXTTOOLS_PACKAGE" "$PACKAGE" || return 1

   echo ""
   echo "Cleaning the package temporary directory."
   sudo rm -rf "$TCEXTTOOLS_PKG_TEMP"

   echo ""
   echo "Packaging the package $PACKAGE completed successfully."

   return 0

}

print_it "Packaging the package $PACKAGE ... \c"
this_main > "$TCEXTTOOLS_MESSAGE_LOG_2" 2>&1
if [ "$?" -gt 0 ]; then
     print_it error "failed!"
     exit 1
fi
print_it hilight "successful!"

exit 0

