#!/bin/sh

############################################################################
#                                                                          #
#                     packageit: Packages the package                      #
#                                                                          #
############################################################################

#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License along
#  with this program; if not, write to the Free Software Foundation, Inc.,
#  51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
#  (C) Copyright 2011 Sercan Arslan
#

. /etc/init.d/tc-functions

TCEXTTOOLS_ROOT="$(dirname $0)/.."

if [ -f "$TCEXTTOOLS_ROOT/etc/init.d/tc-ext-tools.sh" ]; then
     . "$TCEXTTOOLS_ROOT/etc/init.d/tc-ext-tools.sh"
else
     echo "${RED}$(basename $0):${BLUE} tc-ext-tools functions file not found!${NORMAL}"
     exit 1
fi

this_main() {

   echo ""
   echo "Packaging the package $PACKAGE ..."

   echo ""
   echo "Cleaning the package temporary directory."
   [ -d "$PACKAGE_PKG_TEMP" ] && sudo rm -rf "$PACKAGE_PKG_TEMP"
   mkdir -p "$PACKAGE_PKG_TEMP"

   for EXTENSION in $EXTENSIONS
   do
       set_extension

       echo -e "Checking if the extension $PACKAGE_EXTENSION_NAME exists ... \c"
       if [ -f "$PACKAGE_EXTENSION_TCZ" ]; then
            echo "yes"
       else
            echo "no"
            echo "You must create it first!"
            return 1
       fi

       echo "Copying the extension $PACKAGE_EXTENSION_NAME files to the package temporary directory."
       [ -d "$PACKAGE_EXTENSION_PKG_TEMP" ] || mkdir -p "$PACKAGE_EXTENSION_PKG_TEMP"
       cp -f "$PACKAGE_EXTENSION_PKG"/*.tcz* "$PACKAGE_EXTENSION_PKG_TEMP" || return 1
   done

   echo "Copying the package source to the package temporary directory."
   if [ -f "$PACKAGE_SOURCE_CONVERTED" ]; then
        echo "Converted package source detected. Using it instead of the original source."
        cp -f "$PACKAGE_SOURCE_CONVERTED" "$PACKAGE_PKG_TEMP/$PACKAGE" || return 1
   elif [ -f "$PACKAGE_SOURCE" ]; then
        cp -f "$PACKAGE_SOURCE" "$PACKAGE_PKG_TEMP/$PACKAGE" || return 1
   fi

   if [ -f "$PACKAGE_PACKAGE" ]; then
        echo "Previously created package tarball detected, deleting it."
        sudo rm -f "$PACKAGE_PACKAGE"
   fi

   echo "Creating the package tarball."
   tar -C "$PACKAGE_PKG_TEMP" -cvjf "$PACKAGE_PACKAGE" "$PACKAGE" || return 1

   echo "Cleaning the package temporary directory."
   sudo rm -rf "$PACKAGE_PKG_TEMP"

   echo ""
   echo "Packaged the package $PACKAGE successfully."

   return 0

}

print_it "Packaging the package $PACKAGE ... \c"
this_main > "$PACKAGE_MESSAGE_LOG_2" 2>&1
if [ "$?" -gt 0 ]; then
     print_it error "failed!"
     exit 1
fi
print_it hilight "successful!"

exit 0

