#!/bin/sh

############################################################################
#                                                                          #
#                   patchit: Patches the package source                    #
#                                                                          #
############################################################################

#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License along
#  with this program; if not, write to the Free Software Foundation, Inc.,
#  51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
#  (C) Copyright 2011 Sercan Arslan
#

. /etc/init.d/tc-functions

TCEXTTOOLS_ROOT="$(dirname $0)/.."

if [ -f "$TCEXTTOOLS_ROOT/etc/init.d/tc-ext-tools.sh" ]; then
     . "$TCEXTTOOLS_ROOT/etc/init.d/tc-ext-tools.sh"
else
     echo "${RED}$(basename $0):${BLUE} tc-ext-tools functions file not found!${NORMAL}"
     exit 1
fi

if [ -z "$TCEXTTOOLS_SOURCE_TOPDIR" ]; then
     print_it error "You must unpack it first!"
     exit 1
fi

############################################################################ 
#                                this main                                 #
############################################################################

this_main() {

   if [ -f "$TCEXTTOOLS_PATCHES/series" ]; then
        PATCHES=$(cat "$TCEXTTOOLS_PATCHES/series")
        for PATCH in $PATCHES
        do
            if [ "${PATCH#\#}" = "$PATCH" ]; then
                 if [ -f "$TCEXTTOOLS_PATCHES/$PATCH" ]; then
                      patch --directory="$TCEXTTOOLS_SOURCE_TOPDIR" -Np1 -i "$TCEXTTOOLS_PATCHES/$PATCH"
                      if [ "$?" -gt 0 ]; then
                           patch --directory="$TCEXTTOOLS_SOURCE_TOPDIR" -Np0 -i "$TCEXTTOOLS_PATCHES/$PATCH" || return 1
                      fi
                 fi
            fi
        done
   elif [ -d "$TCEXTTOOLS_PATCHES" ]; then
        PATCHES=$(ls "$TCEXTTOOLS_PATCHES")
        if [ -n "$PATCHES" ]; then
             for PATCH in $PATCHES
             do
                 if [ -f "$TCEXTTOOLS_PATCHES/$PATCH" ]; then
                      patch --directory="$TCEXTTOOLS_SOURCE_TOPDIR" -Np1 -i "$TCEXTTOOLS_PATCHES/$PATCH"
                      if [ "$?" -gt 0 ]; then
                           patch --directory="$TCEXTTOOLS_SOURCE_TOPDIR" -Np0 -i "$TCEXTTOOLS_PATCHES/$PATCH" || return 1
                      fi
                 fi
             done
        fi
   fi

   return 0

}

print_it "Patching the package $PACKAGE source ... \c"
this_main > "$TCEXTTOOLS_MESSAGE_LOG_2" 2>&1
if [ "$?" -gt 0 ]; then
     print_it error "failed!"
     exit 1
fi
print_it hilight "successful!"

exit 0

