#!/bin/sh

############################################################################
#                                                                          #
#                   patchit: Patches the package source                    #
#                                                                          #
############################################################################

#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License along
#  with this program; if not, write to the Free Software Foundation, Inc.,
#  51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
#  (C) Copyright 2011 Sercan Arslan
#

. /etc/init.d/tc-functions

TCEXTTOOLS_ROOT="$(dirname $0)/.."

if [ -f "$TCEXTTOOLS_ROOT/etc/init.d/tc-ext-tools.sh" ]; then
     . "$TCEXTTOOLS_ROOT/etc/init.d/tc-ext-tools.sh"
else
     echo "${RED}$(basename $0):${BLUE} tc-ext-tools functions file not found!${NORMAL}"
     exit 1
fi

if [ -z "$TCEXTTOOLS_SOURCE_TOPDIR" ]; then
     print_it error "You must unpack it first!"
     exit 1
fi

############################################################################ 
#                                this main                                 #
############################################################################

this_main() {

   if [ -f "$TCEXTTOOLS_PATCHES/series" ]; then
        echo "Using the series file to detect the package patches."
        PATCHES=$(cat "$TCEXTTOOLS_PATCHES/series")
   elif [ -d "$TCEXTTOOLS_PATCHES" ]; then
        echo "Listing the patch files under the package patches directory."
        PATCHES=$(ls "$TCEXTTOOLS_PATCHES")
   fi

   if [ -n "$PATCHES" ]; then
        for PATCH in $PATCHES
        do
           if [ -d "$TCEXTTOOLS_PATCHES/$PATCH" ]; then
                echo "Skipping the patch $PATCH. It is a directory not a patch!"
                continue
           fi
           for i in $(cat $TCEXTTOOLS_PATCHES/$PATCH | grep "\-\-\-" | cut -f2 -d" " | cut -f1 -d" ")
           do
               if [ -f "$TCEXTTOOLS_SOURCE_TOPDIR/$i" ]; then
                    PATCH_LEVEL=0
               else
                    PATCH_LEVEL=1
               fi
               break
           done
           if [ -f "$TCEXTTOOLS_PATCHES/$PATCH" ]; then
                echo "Applying the patch $PATCH with patch level $PATCH_LEVEL ..."
                patch --directory="$TCEXTTOOLS_SOURCE_TOPDIR" -Np$PATCH_LEVEL -i "$TCEXTTOOLS_PATCHES/$PATCH" || return 1
           fi
           echo "Applied the patch $PATCH successfully."
        done
   fi

   return 0

}

print_it "Patching the package $PACKAGE source ... \c"
this_main > "$TCEXTTOOLS_MESSAGE_LOG_2" 2>&1
if [ "$?" -gt 0 ]; then
     print_it error "failed!"
     exit 1
fi
print_it hilight "successful!"

exit 0

