#!/bin/sh

############################################################################
#                                                                          #
#                  unpackit: Unpacks the package source                    #
#                                                                          #
############################################################################

#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#  Copyright (c) 2011 Sercan Arslan <arslanserc@gmail.com>
#

. /etc/init.d/tc-functions

TCEXTTOOLS_ROOT="$(dirname $0)/.."

if [ -f "$TCEXTTOOLS_ROOT/etc/tc-ext-tools/functions" ]; then
     . "$TCEXTTOOLS_ROOT/etc/tc-ext-tools/functions"
else
     echo "${RED}$(basename $0):${BLUE} tc-ext-tools functions file not found!${NORMAL}"
     exit 1
fi

if [ ! -f "$PACKAGE_SOURCE" ]; then
       print_it --error "You must download it first!"
       exit 1
fi

this_main() {

   echo "---------------------------------------------------------------"
   echo ""
   echo "Unpacking the package $PACKAGE source $PACKAGE_SOURCE_NAME ..."
   echo ""
   echo "---------------------------------------------------------------"

   echo "Cleaning the package src temporary directory."
   [ -d "$PACKAGE_SRC_TEMP" ] && sudo rm -rf "$PACKAGE_SRC_TEMP"
   mkdir -p "$PACKAGE_SRC_TEMP"

   if [ "$PACKAGE_SOURCE_TYPE" = "bz2" ] || [ "$PACKAGE_SOURCE_TYPE" = "gz" ] || [ "$PACKAGE_SOURCE_TYPE" = "tgz" ] || [ "$PACKAGE_SOURCE_TYPE" = "tbz2" ] || [ "$PACKAGE_SOURCE_TYPE" = "xz" ] || [ "$PACKAGE_SOURCE_TYPE" = "txz" ] || [ "$PACKAGE_SOURCE_TYPE" = "tar" ]; then
        echo "---------------------------------------------------------------"
        echo "Extracting the package source by using tar."
        echo "---------------------------------------------------------------"
        tar -C "$PACKAGE_SRC_TEMP" -xvf "$PACKAGE_SOURCE" || return 1
   elif [ "$PACKAGE_SOURCE_TYPE" = "zip" ]; then
        echo "---------------------------------------------------------------"
        echo "Unzipping the package source."
        echo "---------------------------------------------------------------"
        unzip "$PACKAGE_SOURCE" -d "$PACKAGE_SRC_TEMP" || return 1
   elif [ "$PACKAGE_SOURCE_TYPE" = "custom" ]; then
        echo "---------------------------------------------------------------"
        echo "Executing the package build unpack function."
        echo "---------------------------------------------------------------"
        cd "$PACKAGE_SRC_TEMP"
        build_unpack || return 1
   else
        echo "---------------------------------------------------------------"
        echo "Error! Unsupported source type."
        echo "---------------------------------------------------------------"
        return 1
   fi

   echo "---------------------------------------------------------------"
   echo ""
   echo "Unpacked the package $PACKAGE source $PACKAGE_SOURCE_NAME successfully."
   echo ""
   echo "---------------------------------------------------------------"

   return 0

}

print_it "Unpacking the package $PACKAGE source ... \c"
this_main > "$PACKAGE_MESSAGE_LOG_2" 2>&1
if [ "$?" -gt 0 ]; then
     print_it --error "failed!"
     exit 1
fi
print_it --hilight "successful!"

exit 0

