#!/bin/sh
#
#  unpackit: Unpacks the package source
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License along
#  with this program; if not, write to the Free Software Foundation, Inc.,
#  51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
#  (C) Copyright 2010 Sercan Arslan
#

. /etc/init.d/tc-functions

TCEXTTOOLS_ROOT=$(dirname $0)/..

if [ -f "$TCEXTTOOLS_ROOT"/etc/tc-ext-tools/functions ]; then
     . "$TCEXTTOOLS_ROOT"/etc/tc-ext-tools/functions
else
     echo "${RED}$(basename $0):${BLUE} tc-ext-tools functions file not found!${NORMAL}"
     exit 1
fi

if [ ! -e "$TCEXTTOOLS_SRC"/"$SOURCE" ]; then
     print_it error "You must download it first!"
     return 1
fi

this_main() {

  TYPE=""

  [ ! "${SOURCE%.bz2}" = "$SOURCE" ] && TYPE="bz2"
  [ ! "${SOURCE%.gz}" = "$SOURCE" ] && TYPE="gz"
  [ ! "${SOURCE%.tgz}" = "$SOURCE" ] && TYPE="tgz"
  [ ! "${SOURCE%.xz}" = "$SOURCE" ] && TYPE="xz"
  [ ! "${SOURCE%.zip}" = "$SOURCE" ] && TYPE="zip"

  if [ -z "$TYPE" ]; then
       print_it error "The type of $SOURCE is not yet supported!"
       exit 1
  fi

  [ -d "$TCEXTTOOLS_BIN_TEMP" ] && sudo rm -rf $TCEXTTOOLS_BIN_TEMP
  mkdir -p $TCEXTTOOLS_BIN_TEMP

  if [ "$TYPE" = "bz2" ]; then
       tar -C $TCEXTTOOLS_BIN_TEMP -xjf "$TCEXTTOOLS_SRC"/"$SOURCE" || return 1
  elif [ "$TYPE" = "gz" -o "$TYPE" = "tgz" ]; then
       tar -C $TCEXTTOOLS_BIN_TEMP -xzf "$TCEXTTOOLS_SRC"/"$SOURCE" || return 1
  elif [ "$TYPE" = "xz" ]; then
       tar -C $TCEXTTOOLS_BIN_TEMP -xJf "$TCEXTTOOLS_SRC"/"$SOURCE" || return 1
  elif [ "$TYPE" = "zip" ]; then
       unzip "$TCEXTTOOLS_SRC"/"$SOURCE" -d $TCEXTTOOLS_BIN_TEMP || return 1
  fi

  return 0
}

print_it "Unpacking the package $PACKAGE source ... \c"
this_main > $TCEXTTOOLS_ERROR_LOG_2 2>&1
if [ "$?" -gt 0 ]; then
     print_it error "failed!"
     exit 1
fi
print_it hilight "successful!"

exit 0
