#!/bin/sh
#
# Starts KDE4 Desktop Session
# 
# License: GPL
#
# (C) 2010-2011 Sercan Arslan <arslanserc@gmail.com>
#

STARTUP="startkde"
CK_LAUNCH_SESSION=/usr/local/bin/ck-launch-session

if [ -e /usr/local/etc/conf.d/kde4-desktop.conf ] ; then
     . /usr/local/etc/conf.d/kde4-desktop.conf
fi

if [ -x "$CK_LAUNCH_SESSION" -a -z "$XDG_SESSION_COOKIE" ]; then
     STARTUP="$CK_LAUNCH_SESSION $STARTUP"
fi

if [ -n "$SLEEP" ] ; then
     sleep $SLEEP_TIME
fi

exec $STARTUP

