#!/bin/sh

IRON_APP=iron
IRON_ROOT=/usr/local/iron
CHROME_DESKTOP=iron.desktop
CHROME_WRAPPER="$IRON_ROOT/$IRON_APP"
PATH="$IRON_ROOT:$PATH"
CHROME_VERSION_EXTRA="for Tiny Core Linux"

if [ "X$LD_LIBRARY_PATH" = "X" ]; then
  LD_LIBRARY_PATH="$CHROMIUM_ROOT"
else
  LD_LIBRARY_PATH="$CHROMIUM_ROOT:$LD_LIBRARY_PATH"
fi

export PATH LD_LIBRARY_PATH CHROME_WRAPPER CHROME_DESKTOP CHROME_VERSION_EXTRA

exec $IRON_ROOT/$IRON_APP "$@"

