#!/bin/bash

############################################################################
#                                                                          #
#              loadit: Loads the package build dependencies                #
#                                                                          #
############################################################################

#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License along
#  with this program; if not, write to the Free Software Foundation, Inc.,
#  51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
#  (C) Copyright 2011 Sercan Arslan
#

. /etc/init.d/tc-functions

TCEXTTOOLS_ROOT="$(dirname $0)/.."

if [ -f "$TCEXTTOOLS_ROOT/etc/init.d/tc-ext-tools.sh" ]; then
        . "$TCEXTTOOLS_ROOT/etc/init.d/tc-ext-tools.sh"
else
        echo "${RED}$(basename $0):${BLUE} tc-ext-tools functions file not found!${NORMAL}"
        exit 1
fi

this_load() {

   COMMAND="${EXTENSION%%::*}"
   if [ "$COMMAND" = "$EXTENSION" ]; then
        COMMAND=""
   else
        EXTENSION="${EXTENSION#*::}"
   fi

   EXTENSION_TCZ="${EXTENSION%.tcz}.tcz"
   EXTENSION_NAME="${EXTENSION_TCZ%.tcz}"

   echo "Checking if the extension is installed."
   if [ -e "/usr/local/tce.installed/$EXTENSION_NAME" ]; then
        echo "The extension $EXTENSION_NAME is already installed."
        if [ "$COMMAND" = "cp2fs" -a -d "$TCLOOP/$EXTENSION_NAME" ]; then
             echo "Warning! cp2fs command issued for $EXTENSION_NAME but it is mounted before."
        fi
        return 0
   fi

   echo "Checking if the extension exists."
   if [ ! -e "$TCE_DIR/optional/$EXTENSION_TCZ" ]; then
          echo "Downloading the extension $EXTENSION_NAME."
          tce-load -w "$EXTENSION_TCZ" || return 1
   else
       echo "The extension $EXTENSION_NAME is available."
   fi

   echo "Executing the extension load command."
   case "$COMMAND" in
       cp2fs) tce-load -i -c "$EXTENSION_TCZ" || return 1 ;;
       *) tce-load -i "$EXTENSION_TCZ" || return 1 ;;
   esac

   echo "The extension $EXTENSION_NAME is loaded successfully."

   return 0

}

this_main() {

   echo ""
   echo "Loading the package $PACKAGE build dependencies ..."

   for EXTENSION in ${BUILD_DEPENDS[@]}
   do
       if [ -n "$EXTENSION" ] && [ "${EXTENSION#\#}" == "$EXTENSION" ]; then
            echo ""
            echo "Loading the extension $EXTENSION."
            this_load || return 1
       fi
   done

   echo ""
   echo "Loaded the package $PACKAGE build dependencies successfully."

   return 0

}

print_it "Loading the package $PACKAGE build dependencies ... \c"
this_main > "$TCEXTTOOLS_MESSAGE_LOG_2" 2>&1
if [ "$?" -gt 0 ]; then
     print_it error "failed!"
     exit 1
fi
print_it hilight "successful!"

exit 0

