#!/bin/bash

############################################################################
#                                                                          #
#                  unpackit: Unpacks the package source                    #
#                                                                          #
############################################################################

#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License along
#  with this program; if not, write to the Free Software Foundation, Inc.,
#  51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
#  (C) Copyright 2011 Sercan Arslan
#

. /etc/init.d/tc-functions

TCEXTTOOLS_ROOT="$(dirname $0)/.."

if [ -f "$TCEXTTOOLS_ROOT/etc/init.d/tc-ext-tools.sh" ]; then
     . "$TCEXTTOOLS_ROOT/etc/init.d/tc-ext-tools.sh"
else
     echo "${RED}$(basename $0):${BLUE} tc-ext-tools functions file not found!${NORMAL}"
     exit 1
fi

if [ ! -f "$PACKAGE_SOURCE" ]; then
       print_it error "You must download it first!"
       exit 1
fi

this_main() {

   echo ""
   echo "Unpacking the package $PACKAGE source ..."

   echo ""
   echo "Cleaning the package temporary source directory."
   [ -d "$PACKAGE_SRC_TEMP" ] && sudo rm -rf "$PACKAGE_SRC_TEMP"
   mkdir -p "$PACKAGE_SRC_TEMP"

   echo "Unpacking the package source $SOURCE_NAME with the source type $SOURCE_TYPE."
   if [ "$SOURCE_TYPE" = "bz2" ] || [ "$SOURCE_TYPE" = "gz" ] || [ "$SOURCE_TYPE" = "tgz" ] || [ "$SOURCE_TYPE" = "tbz2" ] || [ "$SOURCE_TYPE" = "xz" ] || [ "$SOURCE_TYPE" = "txz" ] || [ "$SOURCE_TYPE" = "tar" ]; then
        echo "Using tar to extract the package source."
        tar -C "$PACKAGE_SRC_TEMP" -xf "$PACKAGE_SOURCE" || return 1
   elif [ "$SOURCE_TYPE" = "zip" ]; then
        echo "Unzipping the package source."
        unzip "$PACKAGE_SOURCE" -d "$PACKAGE_SRC_TEMP" || return 1
   elif [ "$SOURCE_TYPE" = "custom" ]; then
        echo "Executing the custom unpack function defined in the package build."
        cd "$PACKAGE_SRC_TEMP"
        build_unpack || return 1
   else
        echo "Error! unsupported source type."
        return 1
   fi

   echo ""
   echo "Unpacked the package $PACKAGE source successfully."

   return 0

}

print_it "Unpacking the package $PACKAGE source ... \c"
this_main > "$PACKAGE_MESSAGE_LOG_2" 2>&1
if [ "$?" -gt 0 ]; then
     print_it error "failed!"
     exit 1
fi
print_it hilight "successful!"

exit 0

