#!/bin/sh

############################################################################
#                                                                          #
#                      buildit: Builds the package                         #
#                                                                          #
############################################################################

#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#  Copyright (c) 2011 Sercan Arslan <arslanserc@gmail.com>
#

. /etc/init.d/tc-functions

TCEXTTOOLS_ROOT="$(dirname $0)/.."

if [ -f "$TCEXTTOOLS_ROOT/etc/tc-ext-tools/functions" ]; then
     . "$TCEXTTOOLS_ROOT/etc/tc-ext-tools/functions"
else
     echo "${RED}$(basename $0):${BLUE} tc-ext-tools functions file not found!${NORMAL}"
     exit 1
fi

print_usage(){

   echo -e "${TCEXTTOOLS_ERROR_COLOR}${THIS} usage:"
   echo -e "\n\t${TCEXTTOOLS_MESSAGE_COLOR}${THIS} clean|load|download|convert|unpack|patch|configure|compile|install|split|strip|create|check|generate|package|encrypt|print|custom|help${NORMAL}"

}

clean_it() {

   print_it "Cleaning the package $PACKAGE ... \c"
   cleanit > "$PACKAGE_BUILD_LOG" 2>&1
   if [ "$?" -gt 0 ]; then
        print_it --error "failed!"
        print_it --warning "For details: buildit print error"
        exit 1
   fi
   print_it --hilight "successful!"

}

download_it() {

   if [ -f "$PACKAGE_SOURCE_ORIG" -o -f "$PACKAGE_SOURCE_CONV" ]; then
        print_it --warning "The package $PACKAGE source already exists."
        exit 0
   fi

   print_it "Downloading the package $PACKAGE source ... \c"
   downloadit > "$PACKAGE_BUILD_LOG" 2>&1
   if [ "$?" -gt 0 ]; then
        print_it --error "failed!"
        print_it --warning "For details: buildit print error"
        exit 1
   fi
   print_it --hilight "successful!"

}

convert_it() {

   if [ -f "$PACKAGE_SOURCE_CONV" ]; then
        print_it --warning "The package $PACKAGE source converted already exists."
        exit 0
   fi

   print_it "Converting the package $PACKAGE source ... \c"
   convertit > "$PACKAGE_BUILD_LOG" 2>&1
   if [ "$?" -gt 0 ]; then
        print_it --error "failed!"
        print_it --warning "For details: buildit print error"
        exit 1
   fi
   print_it --hilight "successful!"

}

unpack_it() {

   print_it "Unpacking the package $PACKAGE source ... \c"
   unpackit > "$PACKAGE_BUILD_LOG" 2>&1
   if [ "$?" -gt 0 ]; then
        print_it --error "failed!"
        print_it --warning "For details: buildit print error"
        exit 1
   fi
   print_it --hilight "successful!"

}

load_it() {

   print_it "Loading the package $PACKAGE build dependencies ... \c"
   loadit > "$PACKAGE_BUILD_LOG" 2>&1
   if [ "$?" -gt 0 ]; then
        print_it --error "failed!"
        print_it --warning "For details: buildit print error"
        exit 1
   fi
   print_it --hilight  "successful!"

}

patch_it() {

   print_it "Patching the package $PACKAGE source ... \c"
   patchit > "$PACKAGE_BUILD_LOG" 2>&1
   if [ "$?" -gt 0 ]; then
        print_it --error "failed!"
        print_it --warning "For details: buildit print error"
        exit 1
   fi
   print_it --hilight "successful!"

}

configure_it() {

   print_it "Configuring the package $PACKAGE ... \c"
   configureit > "$PACKAGE_BUILD_LOG" 2>&1
   if [ "$?" -gt 0 ]; then
        print_it --error "failed!"
        print_it --warning "For details: buildit print configure"
        exit 1
   fi
   print_it --hilight "successful!"

}

compile_it() {

   print_it "Compiling the package $PACKAGE ... \c"
   compileit > "$PACKAGE_BUILD_LOG" 2>&1
   if [ "$?" -gt 0 ]; then
        print_it --error "failed!"
        print_it --warning "For details: buildit print compile"
        exit 1
   fi
   print_it --hilight "successful!"

}

install_it() {

   print_it "Installing the package $PACKAGE ... \c"
   sudo installit > "$PACKAGE_BUILD_LOG" 2>&1
   if [ "$?" -gt 0 ]; then
        print_it --error "failed!"
        print_it --warning "For details: buildit print install"
        exit 1
   fi
   print_it --hilight "successful!"

}

split_it() {

   print_it "Splitting the package $PACKAGE extensions ... \c"
   splitit > "$PACKAGE_BUILD_LOG" 2>&1
   if [ "$?" -gt 0 ]; then
        print_it --error "failed!"
        print_it --warning "For details: buildit print error"
        exit 1
   fi
   print_it --hilight "successful!"

}

strip_it() {

   print_it "Stripping the package $PACKAGE extensions ... \c"
   stripit > "$PACKAGE_BUILD_LOG" 2>&1
   if [ "$?" -gt 0 ]; then
        print_it --error "failed!"
        print_it --warning "For details: buildit print error"
        exit 1
   fi
   print_it --hilight "successful!"

}

create_it() {

   print_it "Creating the package $PACKAGE extensions ... \c"
   createit > "$PACKAGE_BUILD_LOG" 2>&1
   if [ "$?" -gt 0 ]; then
        print_it --error "failed!"
        print_it --warning "For details: buildit print error"
        exit 1
   fi
   print_it --hilight "successful!"

}

generate_it() {

   print_it "Generating the package $PACKAGE extension info files ... \c"
   generateit > "$PACKAGE_BUILD_LOG" 2>&1
   if [ "$?" -gt 0 ]; then
        print_it --error "failed!"
        print_it --warning "For details: buildit print error"
        exit 1
   fi
   print_it --hilight "successful!"

}

check_it() {

   print_it "Checking the package $PACKAGE extensions ... \c"
   checkit > "$PACKAGE_BUILD_LOG" 2>&1
   if [ "$?" -gt 0 ]; then
        print_it --error "failed!"
        print_it --warning "For details: buildit print error"
        exit 1
   fi
   print_it --hilight "successful!"

}

package_it() {

   print_it "Packaging the package $PACKAGE ... \c"
   packageit > "$PACKAGE_BUILD_LOG" 2>&1
   if [ "$?" -gt 0 ]; then
        print_it --error "failed!"
        print_it --warning "For details: buildit print error"
        exit 1
   fi
   print_it --hilight "successful!"

}

encrypt_it() {

   encryptit || exit 1

}

custom_function() {

   FUNCTION="$1"

   if [ -z "$FUNCTION" ]; then
        print_it --error "You need to specify the name of the custom function."
        exit 1
   fi

   print_it "Executing the package $PACKAGE custom build function $FUNCTION ... \c"
   build_${FUNCTION} > "$PACKAGE_BUILD_LOG" 2>&1
   if [ "$?" -gt 0 ]; then
        print_it --error "failed!"
        print_it --warning "For details: buildit print error"
        exit 1
   fi
   print_it --hilight "successful!"

}

build_it() {

   echo -e "${TCEXTTOOLS_MESSAGE_COLOR}Building the package $PACKAGE started at ${TCEXTTOOLS_HILIGHT_COLOR}$TIME${TCEXTTOOLS_MESSAGE_COLOR}"
   set_date; SECONDS_BEFORE="$SECONDS"
   clean_it || exit 1
   build_rules || exit 1
   set_date; SECONDS_AFTER="$SECONDS"
   echo -e "${TCEXTTOOLS_MESSAGE_COLOR}Building the package $PACKAGE finished at ${TCEXTTOOLS_HILIGHT_COLOR}$TIME${TCEXTTOOLS_MESSAGE_COLOR} in ${TCEXTTOOLS_HILIGHT_COLOR}$(expr $SECONDS_AFTER - $SECONDS_BEFORE)${TCEXTTOOLS_MESSAGE_COLOR} seconds${NORMAL}"
   encrypt_it || exit 1

}

print_function() {

   case "$1" in
       configure)
                if [ -f "$PACKAGE_CONFIGURE_LOG" ]; then
                     cat "$PACKAGE_CONFIGURE_LOG"
                fi
                ;;
       compile)
                if [ -f "$PACKAGE_COMPILE_LOG" ]; then
                     cat "$PACKAGE_COMPILE_LOG"
                fi
                ;;
       install)
                if [ -f "$PACKAGE_INSTALL_LOG" ]; then
                     cat "$PACKAGE_INSTALL_LOG"
                fi
                ;;
       build)
                if [ -f "$PACKAGE_BUILD_LOG" ]; then
                     cat "$PACKAGE_BUILD_LOG"
                     echo -e "${NORMAL}\c"
                fi
                ;;
       message)
                if [ -f "$PACKAGE_MESSAGE_LOG" ]; then
                     cat "$PACKAGE_MESSAGE_LOG"
                     echo -e "${NORMAL}\c"
                fi
                ;;
       *)
                print_it --warning "Usage: buildit print configure|compile|install|build|message"
                ;;
   esac

}

if [ -z "$1" ]; then
     if build_it; then
        exit 0
     else
        exit 1
     fi
fi

case "$1" in
	clean)
		  clean_it
		  ;;
	download)
		  download_it
		  ;;
	convert)
		  convert_it
		  ;;
	unpack)
		  unpack_it
		  ;;
	load)
		  load_it
		  ;;
	patch)
		  patch_it
		  ;;
	configure)
		  configure_it
		  ;;
	compile)
		  compile_it
		  ;;
	install)
		  install_it
		  ;;
	split)
		  split_it
		  ;;
	strip)
		  strip_it
		  ;;
	create)
		  create_it
		  ;;
	check)
		  check_it
		  ;;
	generate)
		  generate_it
		  ;;
	package)
		  package_it
		  ;;
	encrypt)
		  encrypt_it
		  ;;
	print)
		  print_function "$2"
		  ;;
	custom)
		  custom_function "$2"
		  ;;
	*)
		  print_usage
		  ;;
esac

exit 0

