#!/bin/sh

############################################################################
#                                                                          #
#           checkit: Checks the extension for possible errors              #
#                                                                          #
############################################################################

#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#  Copyright (c) 2011 Sercan Arslan <arslanserc@gmail.com>
#

. /etc/init.d/tc-functions

TCEXTTOOLS_ROOT="$(dirname $0)/.."

if [ -f "$TCEXTTOOLS_ROOT/etc/tc-ext-tools/functions" ]; then
     . "$TCEXTTOOLS_ROOT/etc/tc-ext-tools/functions"
else
     echo "${RED}$(basename $0):${BLUE} tc-ext-tools functions file not found!${NORMAL}"
     exit 1
fi

this_check() {

   echo "Cleaning the package extension bin temporary directory."
   [ -d "$PACKAGE_EXTENSION_BIN_TEMP" ] && sudo rm -rf "$PACKAGE_EXTENSION_BIN_TEMP"
   mkdir -p "$PACKAGE_BIN_TEMP"

   echo "Extracting the package extension to the package extension bin temporary directory."
   sudo unsquashfs -d "$PACKAGE_EXTENSION_BIN_TEMP" "$PACKAGE_EXTENSION_TCZ" || return 1

   echo "Checking the package extension files."
   cd "$PACKAGE_EXTENSION_BIN_TEMP"
   sudo find -not -type d -exec file "{}" \; || return 1
   cd -

   echo "Checking the permissions and ownership of the package extension tce.installed directory."
   if [ -d "$PACKAGE_EXTENSION_BIN_TEMP/usr/local/tce.installed" ]; then
        OUT=$(sudo busybox ls -d -l "$PACKAGE_EXTENSION_BIN_TEMP/usr/local/tce.installed")
        PERM=$(echo $OUT | cut -d" " -f1)
        OWNER=$(echo $OUT | cut -d" " -f3-4)

        if [ "$PERM" != "drwxrwxr-x" ] && [ "$PERM" != "drwxrwsr-x" ]; then
             echo "Error! Wrong permissions detected for the package extension $PACKAGE_EXTENSION_NAME tce.installed directory."
             return 1
        fi

        if [ "$OWNER" != "root staff" ]; then
             echo "Error! Wrong ownership detected for the package extension $PACKAGE_EXTENSION_NAME tce.installed directory."
             return 1
        fi

        echo "Checking the permissions and ownership of the package extension tce.installed script."
        if [ -e "$PACKAGE_EXTENSION_BIN_TEMP/usr/local/tce.installed/$PACKAGE_EXTENSION_NAME" ]; then
             OUT=$(sudo busybox ls -l "$PACKAGE_EXTENSION_BIN_TEMP/usr/local/tce.installed/$PACKAGE_EXTENSION_NAME")
             PERM=$(echo $OUT | cut -d" " -f1)
             OWNER=$(echo $OUT | cut -d" " -f3-4)

             if [ "$PERM" != "-rwxrwxr-x" ] && [ "$PERM" != "-rwxrwsr-x" ]; then
                  echo "Error! Wrong permissions detected for the package extension $PACKAGE_EXTENSION_NAME tce.installed script."
                  return 1
             fi

             if [ "$OWNER" != "root staff" ]; then
                  echo "Error! Wrong ownership detected for the package extension $PACKAGE_EXTENSION_NAME tce.installed script."
                  return 1
             fi
        fi
   fi

   return 0

}

this_main() {

   echo "---------------------------------------------------------------"
   echo ""
   echo "Checking the package $PACKAGE extensions ..."
   echo ""
   echo "---------------------------------------------------------------"

   for EXTENSION in $EXTENSIONS
   do
       set_extension

       echo "---------------------------------------------------------------"
       echo "Checking the package extension $PACKAGE_EXTENSION_NAME."
       echo "---------------------------------------------------------------"

       echo -e "Checking if the package extension is created before ... \c"
       if [ -f "$PACKAGE_EXTENSION_TCZ" ]; then
            echo "yes"
       else
            echo "no"
            echo "Error! You must create it first."
            return 1
       fi

       this_check
       if [ "$?" -gt 0 ]; then
            echo "---------------------------------------------------------------"
            echo "Error! Checking the extension $PACKAGE_EXTENSION_NAME failed."
            echo "---------------------------------------------------------------"
            sudo rm -rf "$PACKAGE_EXTENSION_BIN_TEMP"
            return 1
       else
            echo "---------------------------------------------------------------"
            echo "Checking the extension $PACKAGE_EXTENSION_NAME successful."
            echo "---------------------------------------------------------------"
            sudo rm -rf "$PACKAGE_EXTENSION_BIN_TEMP"
       fi
   done

   echo "---------------------------------------------------------------"
   echo ""
   echo "Checked the package $PACKAGE extensions successfully."
   echo ""
   echo "---------------------------------------------------------------"

   return 0

}

echo -e "${MESSAGE_COLOR}Checking the package ${HILIGHT_COLOR}$PACKAGE${MESSAGE_COLOR} extensions ... ${NORMAL}\c"
this_main > "$PACKAGE_MESSAGE_LOG" 2>&1
if [ "$?" -gt 0 ]; then
     echo "${ERROR_COLOR}failed!${NORMAL}"
     echo "${WARNING_COLOR}For details: ${WARNING_COLOR_H}buildit print message${NORMAL}"
     exit 1
fi
echo "${HILIGHT_COLOR}successful!${NORMAL}"

exit 0

