#!/bin/sh
#
#  checkit: Checks the extension for possible errors
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License along
#  with this program; if not, write to the Free Software Foundation, Inc.,
#  51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
#  (C) Copyright 2010 Sercan Arslan
#

. /etc/init.d/tc-functions

TCEXTTOOLS_ROOT=$(dirname $0)/..

if [ -f "${TCEXTTOOLS_ROOT}/etc/tc-ext-tools/functions" ]; then
     . ${TCEXTTOOLS_ROOT}/etc/tc-ext-tools/functions
else
     echo "${RED}$(basename ${0}):${BLUE} tc-ext-tools functions file not found!${NORMAL}"
     exit 1
fi

EXTENSION="${1}"

print_usage(){
  echo -e "${TCEXTTOOLS_ERROR_COLOR}Usage:${TCEXTTOOLS_MESSAGE_COLOR}\n$(basename $0) extension${NORMAL}"
}

if [ -z "${EXTENSION}" ]; then
      print_usage
      exit 1
fi

if [ ! -e "${TCEXTTOOLS_EXTENSIONS}/${EXTENSION}/${EXTENSION}.tcz" ]; then
     print_it error "You must create it first!"
     exit 1
fi

TMP_DIR=$(busybox mktemp -d)
if [ $? -gt 0 ]; then
     print_it error "Creating temp directory failed!"
     exit 1
fi

this_main() {

  sudo busybox mount -o loop ${TCEXTTOOLS_EXTENSIONS}/${EXTENSION}/${EXTENSION}.tcz ${TMP_DIR} || return 1

  FILES=$(sudo find ${TMP_DIR} -not -type d)
  SAVEIFS=${IFS}
  IFS=$(echo -en "\n\b")
  for f in ${FILES}
  do
      sudo file "${f}" || return 1
  done
  IFS=${SAVEIFS}

  sudo busybox umount ${TMP_DIR}
  sudo rm -rf ${TMP_DIR}

  return 0
}

print_it "Checking the extension ${EXTENSION} ... \c"
this_main > ${TCEXTTOOLS_ERROR_LOG_2} 2>&1
if [ $? -gt 0 ]; then
     print_it error "failed!"
     sudo busybox umount ${TMP_DIR} > /dev/null 2>&1
     sudo rm -rf ${TMP_DIR} > /dev/null 2>&1
     exit 1
fi

print_it hilight "successful!"

exit 0
