#!/bin/sh

############################################################################
#                                                                          #
#  compressit: Compresses the directory or file with a compression format  #
#                                                                          #
############################################################################

#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License along
#  with this program; if not, write to the Free Software Foundation, Inc.,
#  51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
#  (C) Copyright 2010 Sercan Arslan
#

. /etc/init.d/tc-functions

TCEXTTOOLS_ROOT="$(dirname $0)/.."

if [ -f "$TCEXTTOOLS_ROOT/etc/tc-ext-tools/functions" ]; then
     . "$TCEXTTOOLS_ROOT/etc/tc-ext-tools/functions"
else
     echo "${RED}$(basename $0):${BLUE} tc-ext-tools functions file not found!${NORMAL}"
     exit 1
fi

FORMAT="$1"
TARGET="$2"
NAME="$3"

print_usage(){

   echo -e "${TCEXTTOOLS_ERROR_COLOR}Usage:${TCEXTTOOLS_MESSAGE_COLOR}\n$(basename $0) bz2|gz|xz /path/to/target name${NORMAL}"

}

if [ -z "$TARGET" ] || [ -z "$FORMAT" ]; then
     print_usage
     exit 1
fi

############################################################################ 
#            compresses the target with a compression format               #
############################################################################

this_compress() {

   if [ -d "$TARGET" ]; then
        TOP_DIR="$(basename $TARGET)"
        if [ -n "$NAME" ]; then
             OUTPUT="${NAME}.tar.${FORMAT}"
        else
             OUTPUT="${TOP_DIR}.tar.${FORMAT}"
        fi

        [ -e "$OUTPUT" ] && sudo rm -f "$OUTPUT"

        tar -C $(dirname $TARGET) -c"${XXX}f" "$OUTPUT" "$TOP_DIR" || return 1

   elif [ -f "$TARGET" ]; then
        if [ -n "$NAME" ]; then
            OUTPUT="${NAME}.${FORMAT}"
        else
            OUTPUT="$(basename $TARGET).${FORMAT}"
        fi

        [ -e "$OUTPUT" ] && sudo rm -f "$OUTPUT"

        "$COMPRESSOR" -c "$TARGET" > "$OUTPUT" || return 1
   fi

   return 0

}

############################################################################ 
#                                this main                                 #
############################################################################

this_main() {

   case "$FORMAT" in
        bz2)
            COMPRESSOR="bzip2"
            XXX=j
            this_compress || return 1
            ;;
        gz)
            COMPRESSOR="gzip"
            XXX="z"
            this_compress || return 1
            ;;
        xz)
            COMPRESSOR="xz"
            XXX="J"
            this_compress || return 1
            ;;
        *)
            return 1
            ;;
   esac

   return 0

}

print_it "Compressing the target $TARGET with the compression format $FORMAT ... \c"
this_main > "$TCEXTTOOLS_ERROR_LOG_2" 2>&1
if [ "$?" -gt 0 ]; then
     print_it error "failed!"
     exit 1
fi
print_it hilight "successful!"

exit 0

