#!/bin/sh

############################################################################
#                                                                          #
#                downloadit: Downloads the package source                  #
#                                                                          #
############################################################################

#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License along
#  with this program; if not, write to the Free Software Foundation, Inc.,
#  51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
#  (C) Copyright 2011 Sercan Arslan
#

. /etc/init.d/tc-functions

TCEXTTOOLS_ROOT="$(dirname $0)/.."

if [ -f "$TCEXTTOOLS_ROOT/etc/init.d/tc-ext-tools.sh" ]; then
     . "$TCEXTTOOLS_ROOT/etc/init.d/tc-ext-tools.sh"
else
     echo "${RED}$(basename $0):${BLUE} tc-ext-tools functions file not found!${NORMAL}"
     exit 1
fi

this_main() {

   [ -d "$TCEXTTOOLS_SRC" ] && sudo rm -rf "$TCEXTTOOLS_SRC"
   mkdir -p "$TCEXTTOOLS_SRC" || return 1

   if [ -n "$SOURCE_URL_TYPE" ]; then
        echo "Applying appropriate operations for url type $SOURCE_URL_TYPE..."

        echo "Cleaning out the temporary source directory..."
        [ -d "$TCEXTTOOLS_SRC_TEMP" ] && sudo rm -rf "$TCEXTTOOLS_SRC_TEMP"
        mkdir -p "$TCEXTTOOLS_SRC_TEMP"
        echo "Cleaned out the temporary source directory."

        cd "$TCEXTTOOLS_SRC_TEMP"

        if [ "$SOURCE_URL_TYPE" = "svn" ]; then
             echo "Checking out svn repository..."
             svn --non-interactive --trust-server-cert co "$SOURCE" "$TCEXTTOOLS_SOURCE_TOPDIR" || return 1
             echo "Checked out svn repository successfully."

             echo "Creating a tarball from the source..."
             tar --exclude-vcs -cvJf "$SOURCE_NAME" "$SOURCE_TOPDIR" || return 1
             echo "Created the tarball successfully."

             echo "Moving the tarball to the package source directory..."
             busybox mv -f "$SOURCE_NAME" "$TCEXTTOOLS_SRC" || return 1
             echo "Moved the tarball to the package source directory successfully."
        elif [ "$SOURCE_URL_TYPE" = "git" ]; then
             echo "Checking out git repository..."
             git clone "$SOURCE" "$TCEXTTOOLS_SOURCE_TOPDIR" || return 1
             echo "Checked out git repository successfully."

             echo "Creating a tarball from the source..."
             tar --exclude-vcs -cvJf "$SOURCE_NAME" "$SOURCE_TOPDIR" || return 1
             echo "Created the tarball successfully."

             echo "Moving the tarball to the package source directory..."
             busybox mv -f "$SOURCE_NAME" "$TCEXTTOOLS_SRC" || return 1
             echo "Moved the tarball to the package source directory successfully."
        fi
        echo "Applied all operations successfully."
   else
        echo "Downloading the source $SOURCE_NAME from url $SOURCE..."
        wget --no-check-certificate "$SOURCE" -O "$TCEXTTOOLS_SOURCE" || return 1
        echo "Downloaded the source $SOURCE_NAME from url $SOURCE successfully."
   fi

   return 0

}

print_it "Downloading the package $PACKAGE source ... \c"
this_main > "$TCEXTTOOLS_DOWNLOAD_LOG" 2>&1
if [ "$?" -gt 0 ]; then
     print_it error "failed!"
     exit 1
fi
print_it hilight "successful!"

exit 0

