#!/bin/sh

############################################################################
#                                                                          #
#                downloadit: Downloads the package source                  #
#                                                                          #
############################################################################

#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License along
#  with this program; if not, write to the Free Software Foundation, Inc.,
#  51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
#  (C) Copyright 2010 Sercan Arslan
#

. /etc/init.d/tc-functions

TCEXTTOOLS_ROOT="$(dirname $0)/.."

if [ -f "$TCEXTTOOLS_ROOT/etc/tc-ext-tools/functions" ]; then
     . "$TCEXTTOOLS_ROOT/etc/tc-ext-tools/functions"
else
     echo "${RED}$(basename $0):${BLUE} tc-ext-tools functions file not found!${NORMAL}"
     exit 1
fi

############################################################################ 
#                                this main                                 #
############################################################################

this_main() {

   [ -d "$TCEXTTOOLS_SRC" ] && sudo rm -rf "$TCEXTTOOLS_SRC"
   mkdir -p "$TCEXTTOOLS_SRC" || return 1

   if [ "$VCS" = "svn" ]; then
        [ -d "$TCEXTTOOLS_SRC_TEMP" ] && sudo rm -rf "$TCEXTTOOLS_SRC_TEMP"
        mkdir -p "$TCEXTTOOLS_SRC_TEMP"
        svn --non-interactive --trust-server-cert co "$SOURCE" "$TCEXTTOOLS_SRC_TEMP/$TOP_SRC" || return 1
        compressit xz "$TCEXTTOOLS_SRC_TEMP/$TOP_SRC" --exclude-vcs || return 1
        busybox mv -f "${TOP_SRC}.tar.xz" "$TCEXTTOOLS_SRC" || return 1
   elif [ "$VCS" = "git" ]; then
        [ -d "$TCEXTTOOLS_SRC_TEMP" ] && sudo rm -rf "$TCEXTTOOLS_SRC_TEMP"
        mkdir -p "$TCEXTTOOLS_SRC_TEMP"
        git clone "$SOURCE" "$TCEXTTOOLS_SRC_TEMP/$TOP_SRC" || return 1
        compressit xz "$TCEXTTOOLS_SRC_TEMP/$TOP_SRC" --exclude-vcs || return 1
        busybox mv -f "${TOP_SRC}.tar.xz" "$TCEXTTOOLS_SRC" || return 1
   elif [ -z "$VCS" ]; then
        busybox wget --no-check-certificate "$SOURCE" -O "$TCEXTTOOLS_SRC/$SOURCE_NAME" || return 1
   else
        echo "Error! Unsupported source type."
        return 1
   fi

   return 0

}

print_it "Downloading the package $PACKAGE source ... \c"
this_main > "$TCEXTTOOLS_DOWNLOAD_LOG" 2>&1
if [ "$?" -gt 0 ]; then
     print_it error "failed!"
     exit 1
fi
print_it hilight "successful!"

exit 0

