#!/bin/sh

############################################################################
#                                                                          #
#       encryptit: Encrypts the file with the default encryption key       #
#                                                                          #
############################################################################

#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License along
#  with this program; if not, write to the Free Software Foundation, Inc.,
#  51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
#  (C) Copyright 2011 Sercan Arslan
#

. /etc/init.d/tc-functions

TCEXTTOOLS_ROOT="$(dirname $0)/.."

if [ -f "$TCEXTTOOLS_ROOT/etc/init.d/tc-ext-tools.sh" ]; then
     . "$TCEXTTOOLS_ROOT/etc/init.d/tc-ext-tools.sh"
else
     echo "${RED}$(basename $0):${BLUE} tc-ext-tools functions file not found!${NORMAL}"
     exit 1
fi

FILE="$1"

print_usage(){

   echo -e "${TCEXTTOOLS_ERROR_COLOR}${THIS} usage:\n\t${TCEXTTOOLS_MESSAGE_COLOR}${THIS} /path/to/file${NORMAL}"

}

if [ -z "$FILE" ] || [ ! -e "$FILE" ]; then
      print_usage
      exit 1
fi

############################################################################ 
#                                this main                                 #
############################################################################

this_main() {

   [ -e "${PACKAGE}.tar.bz2.bfe" ] && sudo rm -f "${PACKAGE}.tar.bz2.bfe"

   bcrypt "$FILE" || return 1

   return 0

}

print_it "Please enter the encryption key: \c"
print_it hilight "$TCEXTTOOLS_ENCRYPTION_KEY"
this_main
if [ "$?" -gt 0 ]; then
     exit 1
fi

exit 0

