#!/bin/sh

############################################################################
#                                                                          #
#       encryptit: Encrypts the file with the default encryption key       #
#                                                                          #
############################################################################

#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License along
#  with this program; if not, write to the Free Software Foundation, Inc.,
#  51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
#  (C) Copyright 2011 Sercan Arslan
#

. /etc/init.d/tc-functions

TCEXTTOOLS_ROOT="$(dirname $0)/.."

if [ -f "$TCEXTTOOLS_ROOT/etc/init.d/tc-ext-tools.sh" ]; then
     . "$TCEXTTOOLS_ROOT/etc/init.d/tc-ext-tools.sh"
else
     echo "${RED}$(basename $0):${BLUE} tc-ext-tools functions file not found!${NORMAL}"
     exit 1
fi

if [ ! -f "$TCEXTTOOLS_PACKAGE" ]; then
       print_it error "You must package it first!"
       return 1
fi

this_main() {

   echo "" > "$TCEXTTOOLS_MESSAGE_LOG_2"

   if [ -f "$TCEXTTOOLS_PACKAGE_ENCRYPTED" ]; then
        echo "The package tarball encrypted detected. Deleting it..." >> "$TCEXTTOOLS_MESSAGE_LOG_2"
        sudo rm -f "$TCEXTTOOLS_PACKAGE_ENCRYPTED"
   fi

   echo "" >> "$TCEXTTOOLS_MESSAGE_LOG_2"
   echo "Encrypting the package tarball ..." >> "$TCEXTTOOLS_MESSAGE_LOG_2"
   print_it "Please enter the encryption key: \c"
   print_it hilight "$TCEXTTOOLS_ENCRYPTION_KEY"
   bcrypt "$TCEXTTOOLS_PACKAGE" || return 1
   echo "Encrypted the package tarball successfully." >> "$TCEXTTOOLS_MESSAGE_LOG_2"

   return 0

}

print_it "Encrypting the package $PACKAGE ..."
this_main
if [ "$?" -gt 0 ]; then
     print_it error "Encrypting the package $PACKAGE failed!"
     exit 1
fi

exit 0

