#!/bin/sh

############################################################################
#                                                                          #
#              loadit: Loads the package build dependencies                #
#                                                                          #
############################################################################

#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License along
#  with this program; if not, write to the Free Software Foundation, Inc.,
#  51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
#  (C) Copyright 2011 Sercan Arslan
#

. /etc/init.d/tc-functions

TCEXTTOOLS_ROOT="$(dirname $0)/.."

if [ -f "$TCEXTTOOLS_ROOT/etc/init.d/tc-ext-tools.sh" ]; then
        . "$TCEXTTOOLS_ROOT/etc/init.d/tc-ext-tools.sh"
else
        echo "${RED}$(basename $0):${BLUE} tc-ext-tools functions file not found!${NORMAL}"
        exit 1
fi

############################################################################ 
#                              load extension                              #
############################################################################

this_load() {

   COMMAND="${EXTENSION%::*}"
   EXTENSION="${EXTENSION#*::}"

   if [ "${EXTENSION#\#}" != "$EXTENSION" ]; then
        echo "The extension $EXTENSION is commented out."
        return 0
   fi

   EXTENSION_TCZ="${EXTENSION%.tcz}.tcz"
   EXTENSION_NAME="${EXTENSION_TCZ%.tcz}"

   if [ -e "/usr/local/tce.installed/$EXTENSION_NAME" ]; then
        echo "The extension $EXTENSION_NAME is already installed."
        if [ "$COMMAND" = "cp2fs" -a -d "$TCLOOP/$EXTENSION_NAME" ]; then
             echo "Warning! cp2fs command issued for $EXTENSION_NAME but it is mounted before."
        fi
        return 0
   fi

   if [ ! -e "$TCE_DIR/optional/$EXTENSION_TCZ" ]; then
          echo "Downloading the extension $EXTENSION_NAME"
          tce-load -w "$EXTENSION_TCZ" || return 1
   else
       echo "The extension $EXTENSION_NAME is already downloaded."
   fi

   case "$COMMAND" in
       cp2fs) tce-load -i -c "$EXTENSION_TCZ" || return 1 ;;
       *) tce-load -i "$EXTENSION_TCZ" || return 1 ;;
   esac

   echo "The extension $EXTENSION_NAME is loaded successfully."

   return 0

}

############################################################################ 
#                                this main                                 #
############################################################################

this_main() {

   if [ -n "$BUILD_DEPENDS" ]; then
        BUILD_DEPENDS="$TCEXTTOOLS_DEPENDS $BUILD_DEPENDS"
   else
        BUILD_DEPENDS="$TCEXTTOOLS_DEPENDS"
   fi

   for EXTENSION in $BUILD_DEPENDS
   do
       if [ -n "$EXTENSION" ]; then
            this_load || return 1
       fi
   done

   return 0

}

print_it "Loading the package $PACKAGE build dependencies ... \c"
this_main > "$TCEXTTOOLS_MESSAGE_LOG_2" 2>&1
if [ "$?" -gt 0 ]; then
     print_it error "failed!"
     exit 1
fi
print_it hilight "successful!"

exit 0

