#!/bin/sh
#
#  packageit: Packages the package
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License along
#  with this program; if not, write to the Free Software Foundation, Inc.,
#  51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
#  (C) Copyright 2010 Sercan Arslan
#

. /etc/init.d/tc-functions

TCEXTTOOLS_ROOT=$(dirname $0)/..

if [ -f "$TCEXTTOOLS_ROOT"/etc/tc-ext-tools/functions ]; then
     . "$TCEXTTOOLS_ROOT"/etc/tc-ext-tools/functions
else
     echo "${RED}$(basename $0):${BLUE} tc-ext-tools functions file not found!${NORMAL}"
     exit 1
fi

this_main() {

  cd $PACKAGE_ROOT

  for EXTENSION in $EXTENSIONS
  do
      if [ ! -d "$TCEXTTOOLS_EXTENSIONS"/"$EXTENSION" ]; then
           print_it error "You must create it first!"
           exit 1
      fi

      [ -d "$TCEXTTOOLS_PKG"/"$EXTENSION" ] || mkdir -p "$TCEXTTOOLS_PKG"/"$EXTENSION"

      busybox cp -f "$TCEXTTOOLS_EXTENSIONS"/"$EXTENSION"/*.tcz* "$TCEXTTOOLS_PKG"/"$EXTENSION" || return 1
  done

  if [ -d "$PACKAGE_SRC" ]; then
       compressit xz $PACKAGE_SRC || return 1
       SRC=$(basename $PACKAGE_SRC).tar.xz
       busybox mv -f $SRC $TCEXTTOOLS_PKG || return 1
  fi

  [ ! "${SOURCE%.bz2}" = "$SOURCE" ] && TYPE="bz2"
  [ ! "${SOURCE%.gz}" = "$SOURCE" ] && TYPE="gz"
  [ ! "${SOURCE%.tgz}" = "$SOURCE" ] && TYPE="tgz"
  [ ! "${SOURCE%.xz}" = "$SOURCE" ] && TYPE="xz"
  [ ! "${SOURCE%.zip}" = "$SOURCE" ] && TYPE="zip"

  if [ "$TYPE" = "bz2" ]; then
       if [ -e "$TCEXTTOOLS_SRC"/"${SOURCE%.bz2}.xz" ]; then
            busybox cp -f "$TCEXTTOOLS_SRC"/"${SOURCE%.bz2}.xz" $TCEXTTOOLS_PKG || return 1
       fi
  elif [ "$TYPE" = "gz" ]; then
       if [ -e "$TCEXTTOOLS_SRC"/"${SOURCE%.gz}.xz" ]; then
            busybox cp -f "$TCEXTTOOLS_SRC"/"${SOURCE%.gz}.xz" $TCEXTTOOLS_PKG || return 1
       fi
  elif [ "$TYPE" = "tgz" ]; then
       if [ -e "$TCEXTTOOLS_SRC"/"${SOURCE%.tgz}.tar.xz" ]; then
            busybox cp -f "$TCEXTTOOLS_SRC"/"${SOURCE%.tgz}.tar.xz" $TCEXTTOOLS_PKG || return 1
       fi
  elif [ "$TYPE" = "xz" ]; then
       busybox cp -f "$TCEXTTOOLS_SRC"/"$SOURCE" $TCEXTTOOLS_PKG || return 1
  elif [ "$TYPE" = "zip" ]; then
       if [ -e "$TCEXTTOOLS_SRC"/"${SOURCE%.zip}.tar.xz" ]; then
            busybox cp -f "$TCEXTTOOLS_SRC"/"${SOURCE%.zip}.tar.xz" $TCEXTTOOLS_PKG || return 1
       fi
  fi

  return 0
}

print_it "Packaging the package $PACKAGE ... \c"
this_main > $TCEXTTOOLS_ERROR_LOG_2 2>&1
if [ "$?" -gt 0 ]; then
     print_it error "failed!"
     exit 1
fi
print_it hilight "successful!"

exit 0
