#!/bin/sh

############################################################################
#                                                                          #
#               splitit: Splits the package into extensions                #
#                                                                          #
############################################################################

#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License along
#  with this program; if not, write to the Free Software Foundation, Inc.,
#  51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
#  (C) Copyright 2011 Sercan Arslan
#

. /etc/init.d/tc-functions

TCEXTTOOLS_ROOT="$(dirname $0)/.."

if [ -f "$TCEXTTOOLS_ROOT/etc/init.d/tc-ext-tools.sh" ]; then
     . "$TCEXTTOOLS_ROOT/etc/init.d/tc-ext-tools.sh"
else
     echo "${RED}$(basename $0):${BLUE} tc-ext-tools functions file not found!${NORMAL}"
     exit 1
fi

if [ ! -d "$TCEXTTOOLS_INSTALL_ROOT" ]; then
       print_it error "You must install it first!"
       exit 1
fi

this_split() {

   echo ""
   echo "Getting the contents of the extension install ..."
   CONTENTS=$(cat $PACKAGE_EXTENSION_INSTALL)
   if [ -z "$CONTENTS" ]; then
        echo "Error! the extension install is empty."
        return 1
   fi
   echo "CONTENTS = $CONTENTS"
   echo ""

   echo ""
   echo "Touching install.list and x-install.list files."
   LIST="${TCEXTTOOLS_BIN_TEMP}/install.list"
   X_LIST="${TCEXTTOOLS_BIN_TEMP}/x-install.list"
   touch "$LIST"
   touch "$X_LIST"
   echo ""

   echo ""
   echo "Processing the extension install contents ..."
   cd "$TCEXTTOOLS_INSTALL_ROOT"
   for i in $CONTENTS
   do
       echo ""
       echo "Processing the content $i ..."

       echo ""
       echo "Checking if the content is commented out ..."
       if [ "${i#\#}" != "$i" ]; then
            echo "The content $i is commented out. Skipping it."
            continue
       fi
       echo ""

       echo ""
       echo "Evaluating the content $i ..."
       i=$(eval echo $i)
       echo "The content is $i after the evaluation."
       echo ""

       echo ""
       echo "Checking if a special wildcard used."
       if [ -n "$(echo "$i" | grep '*')" ]; then
            echo "The wildcard * found in the content."
       fi
       echo ""

       echo ""
       if [ -z "$(echo "$i" | grep '*')" ]; then
            if [ "${i#x-}" = "$i" ]; then
                 echo "Putting the files in the content to the include list."
                 sudo find "$i" -not -type d >> "$LIST" || return 1
            else
                 i="${i#x-}"
                 echo "Putting the files in the content to the exclude list."
                 sudo find "$i" -not -type d >> "$X_LIST" || return 1
            fi
       else
            if [ "${i#x-}" = "$i" ]; then
                 echo "Putting the files in the content to the include list."
                 sudo find $i -not -type d >> "$LIST" || return 1
            else
                 i="${i#x-}"
                 echo "Putting the files in the content to the exclude list."
                 sudo find $i -not -type d >> "$X_LIST" || return 1
            fi
       fi
       echo ""
   done
   echo ""

   echo ""
   echo "Creating the extension contents tarball from the include and the exclude lists."
   sudo tar -T "$LIST" -X "$X_LIST" -cvpzf "$TCEXTTOOLS_BIN_TEMP/pkg.tar.gz" || return 1
   echo ""

   echo "Cleaning the package extension bin directory."
   [ -d "$TCEXTTOOLS_EXTENSION_BINDIR" ] && sudo rm -rf "$TCEXTTOOLS_EXTENSION_BINDIR"
   sudo mkdir -p "$TCEXTTOOLS_EXTENSION_BINDIR"

   echo ""
   echo "Extracting the extension contents tarball to the extension bin directory."
   sudo mkdir -p "$TCEXTTOOLS_EXTENSION_BINDIR"
   sudo tar -C "$TCEXTTOOLS_EXTENSION_BINDIR" -pvxzf "$TCEXTTOOLS_BIN_TEMP/pkg.tar.gz" || return 1
   echo ""

   echo ""
   echo "Cleaning the extension bin temporary directory."
   sudo rm -rf "$TCEXTTOOLS_BIN_TEMP"
   echo ""

   return 0

}

this_main() {

   echo ""
   echo "Starting the splitting process for the package $PACKAGE ..."

   for EXTENSION in $EXTENSIONS
   do
       echo ""
       echo "Processing the extension $EXTENSION ..."

       echo ""
       echo "Setting the extension parameters."
       set_extension || return 1

       echo ""
       echo "Cleaning the package bin temporary directory."
       [ -d "$TCEXTTOOLS_BIN_TEMP" ] && sudo rm -rf "$TCEXTTOOLS_BIN_TEMP"
       mkdir -p "$TCEXTTOOLS_BIN_TEMP"

       echo ""
       echo "Splitting the extension $EXTENSION_NAME ..."
       this_split
       if [ "$?" -gt 0 ]; then
            echo "Error! splitting the extension $EXTENSION_NAME failed."
            sudo rm -rf "$TCEXTTOOLS_BIN_TEMP"
            return 1
       else
            echo "Splitting the extension $EXTENSION_NAME successful."
       fi
   done

   echo ""
   echo "Splitted the package $PACKAGE extensions successfully."

   return 0

}

print_it "Splitting the package $PACKAGE extensions ... \c"
this_main > "$TCEXTTOOLS_MESSAGE_LOG_2" 2>&1
if [ "$?" -gt 0 ]; then
     print_it error "failed!"
     exit 1
fi
print_it hilight "successful!"

exit 0

