#!/bin/sh

############################################################################
#                                                                          #
#               splitit: Splits the package into extensions                #
#                                                                          #
############################################################################

#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License along
#  with this program; if not, write to the Free Software Foundation, Inc.,
#  51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
#  (C) Copyright 2011 Sercan Arslan
#

. /etc/init.d/tc-functions

TCEXTTOOLS_ROOT="$(dirname $0)/.."

if [ -f "$TCEXTTOOLS_ROOT/etc/init.d/tc-ext-tools.sh" ]; then
     . "$TCEXTTOOLS_ROOT/etc/init.d/tc-ext-tools.sh"
else
     echo "${RED}$(basename $0):${BLUE} tc-ext-tools functions file not found!${NORMAL}"
     exit 1
fi

if [ ! -d "$TCEXTTOOLS_INSTALL_ROOT" ]; then
       print_it error "You must install it first!"
       exit 1
fi

############################################################################ 
#                splits the files out of install root                      #
############################################################################

this_split() {

   CONTENTS=$(cat $PACKAGE_EXTENSION_INSTALL)
   [ -z "$CONTENTS" ] && return 1

   LIST="${TMP_DIR}/install.list"
   X_LIST="${TMP_DIR}/x-install.list"

   touch "$LIST" || return 1
   touch "$X_LIST" || return 1

   cd "$TCEXTTOOLS_INSTALL_ROOT"

   for i in $CONTENTS
   do
       i=$(eval echo $i)
       if [ -z "$(echo "$i" | grep '*')" ]; then
               if [ "${i#\#}" = "$i" ]; then
                    if [ "${i#x-}" = "$i" ]; then
                         sudo find "$i" -not -type d >> "$LIST" || return 1
                    else
                         i="${i#x-}"
                         sudo find "$i" -not -type d >> "$X_LIST" || return 1
                    fi
               fi
       else
               if [ "${i#\#}" = "$i" ]; then
                    if [ "${i#x-}" = "$i" ]; then
                         sudo find $i -not -type d >> "$LIST" || return 1
                    else
                         i="${i#x-}"
                         sudo find $i -not -type d >> "$X_LIST" || return 1
                    fi
               fi
       fi
   done

   sudo tar -T "$LIST" -X "$X_LIST" -cpzf "$TMP_DIR/pkg.tar.gz" || return 1
   sudo mkdir -p "$TMP_DIR/root" || return 1
   sudo tar -C "$TMP_DIR/root" -pxzf "$TMP_DIR/pkg.tar.gz" || return 1

   if [ -d "$TCEXTTOOLS_BIN/$EXTENSION_NAME" ]; then
        sudo rm -rf "$TCEXTTOOLS_BIN/$EXTENSION_NAME" || return 1
   fi

   sudo mv "$TMP_DIR/root" "$TCEXTTOOLS_BIN/$EXTENSION_NAME" || return 1

   sudo rm -rf "$TMP_DIR"

   return 0

}

############################################################################ 
#                                this main                                 #
############################################################################

this_main() {

   for EXTENSION in $EXTENSIONS
   do
       set_extension || return 1

       TMP_DIR=$(busybox mktemp -d)
       if [ ! -d "$TMP_DIR" ]; then
              print_it error "Creating a temporary directory for splitting the extension $EXTENSION_NAME failed!"
              return 1
       fi

       this_split
       if [ "$?" -gt 0 ]; then
            print_it error "Splitting the extension $EXTENSION_NAME failed!"
            sudo rm -rf "$TMP_DIR"
            return 1
       else
            print_it "Splitting the extension $EXTENSION_NAME successful!"
       fi
   done

   return 0

}

print_it "Splitting the package $PACKAGE extensions ... \c"
this_main > "$TCEXTTOOLS_MESSAGE_LOG_2" 2>&1
if [ "$?" -gt 0 ]; then
     print_it error "failed!"
     exit 1
fi
print_it hilight "successful!"

exit 0

