#!/bin/sh

############################################################################
#                                                                          #
#           stripit: Strips the unneccessary debugging symbols             #
#                                                                          #
############################################################################

#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License along
#  with this program; if not, write to the Free Software Foundation, Inc.,
#  51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
#  (C) Copyright 2011 Sercan Arslan
#

. /etc/init.d/tc-functions

TCEXTTOOLS_ROOT="$(dirname $0)/.."

if [ -f "$TCEXTTOOLS_ROOT/etc/init.d/tc-ext-tools.sh" ]; then
     . "$TCEXTTOOLS_ROOT/etc/init.d/tc-ext-tools.sh"
else
     echo "${RED}$(basename $0):${BLUE} tc-ext-tools functions file not found!${NORMAL}"
     exit 1
fi

TARGET_DIR="$1"

print_usage(){

   echo -e "${TCEXTTOOLS_ERROR_COLOR}${THIS} usage:\n\t${TCEXTTOOLS_MESSAGE_COLOR}${THIS} /path/to/directory${NORMAL}"

}

if [ -z "$TARGET_DIR" ] || [ ! -d "$TARGET_DIR" ]; then
      print_usage
      exit 1
fi

############################################################################ 
#                                this main                                 #
############################################################################

this_main() {

   EXE_LIST=$(sudo find "$TARGET_DIR" | xargs sudo file | grep "executable" | grep ELF | grep "not stripped" | cut -f 1 -d :)
   SO_LIST=$(sudo find "$TARGET_DIR" | xargs sudo file | grep "shared object" | grep ELF | grep "not stripped" | cut -f 1 -d :)

   if [ -n "$EXE_LIST" ]; then
        for i in $EXE_LIST
        do
            sudo strip --strip-unneeded "$i" || return 1
        done
   fi

   if [ -n "$SO_LIST" ]; then
        for i in $SO_LIST
        do
            sudo strip -g "$i" || return 1
        done
   fi

   return 0

}

print_it "Stripping the files in the target directory ... \c"
this_main > "$TCEXTTOOLS_MESSAGE_LOG_2" 2>&1
if [ "$?" -gt 0 ]; then
     print_it error "failed!"
     exit 1
fi
print_it hilight "successful!"

exit 0

